#!/usr/bin/env node

/**
* Perkins v2.0.3 CLI by Carlos Elias
*/

var path     = require('path'),
    perkins  = require('commander'),
    core     = require('./lib/core.js'),
    server   = require('./lib/preview.js'),
    cli      = require('./lib/cli.js')(),
    colors   = require('/usr/lib/node_modules/colors');

perkins
  .version('Perkins 2.0.3'.bold)
  .usage('[command] --options <dir>')
  .option('-p, --port <port>', 'specify the port [8000]', Number, 8000)
  .option('-m, --min', 'minifies Perkins into a css file.', false)
  .option('-v, --verbose', 'output incoming requests.', false)

perkins
  .command('preview [path]')
  .description('This option create a Perkins Preview HTTP Server')
  .action(function(dir){
    if (path.existsSync(dir)) {
      server.preview(dir);
      cli.msg('Your preview server for '+dir+' is ready, Sir. on http://localhost:'+perkins.port);
      cli.info('You want to stop the preview? press Ctrl+C');
    } else {
      cli.error('Sorry, Sir but '+dir+' do not exists...');
    }
  });
  
perkins
  .command('setup <path>')
  .description('Just relax let me take care of building a version of ... well me.')
  .action(function(dir){
    core.setup(dir);
  });

perkins
  .command('watch <path>')
  .description('watch feature test')
  .action(function(dir) {
    if (path.existsSync(dir)) {
      cli.info('Start watching');
      core.watch(dir);
    }
    else {
      cli.error('Sorry, Sir but '+ dir +' does not exists');
    }
  });

perkins
  .command('debug [path]')
  .description('Don\'t take me seriously... just for internal tests')
  .action(function(dir) {
    
  });

perkins
  .command('pre [path]')
  .description('Don\'t take me seriously... just for internal tests')
  .action(function(dir) {

  });

perkins.parse(process.argv);
